import Header from "@/components/Header";
import "../styles/globals.css";
import PromptInput from "@/components/PromptInput";
import ClientProvider from "@/components/ClientProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Client provider is to wrap whole app to be able use React hot toast */}
        <ClientProvider>
          {/* Header */}
          <Header />
          {/* Prompt input */}
          <PromptInput />
          <div>{children}</div>
        </ClientProvider>
      </body>
    </html>
  );
}
